#/bin/bash

# Copyright (c) 2005 MichalDominik (AT) gmail (DOT) com ; MIT X11 license
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
# THE USE OR OTHER DEALINGS IN THE SOFTWARE.

######################### MODIFY HERE FOR YOUR NEEDS ########################

EXTENSIONS=".*\.tex$"               # Files to parse
AFTERLINES=10                           # Number of context lines after
BEFORELINES=3                           # Number of context lines before
PROJECT="Rich's Thesis FIXMEs"
NOTE="This file was generated by fixme2html."

################################## BANNER ###################################

echo 
echo "/- fixme2html by MDK ---------------------------------------"
echo "|" 
echo "| Generates a nice DOM HTML file out of the FIXMEs contained"
echo "| in source files. Modify this script to fit your needs."
echo "|"

if [ -z "$1" ] ; then
        echo "| Usage: fixme2hmtl.sh outputfile"
        echo "|"
        echo "| You should run this script in the root directory of your"
        echo "| project"
        echo
        exit
fi
echo

############################# MAIN PROCESSING #################################

# Poormans method of clearing a file
echo "" > $1

# Find files for each extension
for extension in $EXTENSIONS
do
        OLDIFS=$IFS
        IFS=:
        FILES=""
        FILES=`find ./ -iregex "$extension" -printf "%p$IFS"`
        if [ -n "$FILES" ] ; then ALLFILES="$FILES$IFS$ALLFILES" ; fi
        IFS=$OLDIFS
done

OLDIFS=$IFS
IFS=:

ID=1

# For each file find fixmes
for file in $ALLFILES
do
        if [ -z "$file" ] ; then continue; fi

        FIXMES=`grep 'FIXME' $file`
        if [ -z "$FIXMES" ] ; then continue; fi

        echo "<h3>$file</h3>" >>$1

        
        IFS="
"
        for fix in $FIXMES
        do
                MESSAGE="$fix"
                CONTEXT=`grep -n -A "$AFTERLINES" -B "$BEFORELINES" "$fix" $file`
                echo "<div id=\"m$ID\" class=\"mhead\">" >>$1
                echo "<p class=\"header\">$fix</p>" >>$1
                echo "<div class=\"submenu\" id=\"s$ID\">" >>$1
                echo "<pre>" >>$1
                echo "$CONTEXT" >>$1
                echo "</pre>" >>$1
                echo "</div>" >>$1
                echo "</div>" >>$1
                let "ID=ID+1"
        done
        IFS=:
done

################################ HTML STUFF ###################################

CONTENT=`cat $1`
echo '
<html>
<script language="JavaScript" type="text/javascript">
<!--
var isNav4, isNav6, isIE4;

/*
 * Browser version snooper; determines your browser
 * (Navigator 4, Navigator 6, or Internet Explorer 4/5)
 */
function setBrowser()
{
    if (navigator.appVersion.charAt(0) == "4")
    {
        if (navigator.appName.indexOf("Explorer") >= 0)
        {
            isIE4 = true;
        }
        else
        {
            isNav4 = true;
        }
    }
    else if (navigator.appVersion.charAt(0) > "4")
    {
        isNav6 = true;
    }
}

/*
 *
 * Given a selector string, return a style object
 * by searching through stylesheets. Return null if
 * none found
 *
 */
function getStyleBySelector( selector )
{
    if (!isNav6)
    {
        return null;
    }
    var sheetList = document.styleSheets;
    var ruleList;
    var i, j;

    /* look through stylesheets in reverse order that
       they appear in the document */
    for (i=sheetList.length-1; i >= 0; i--)
    {
        ruleList = sheetList[i].cssRules;
        for (j=0; j<ruleList.length; j++)
        {
            if (ruleList[j].type == CSSRule.STYLE_RULE &&
                ruleList[j].selectorText == selector)
            {
                return ruleList[j].style;
            }   
        }
    }
    return null;
}

/*
 *
 * Given an id and a property (as strings), return
 * the given property of that id.  Navigator 6 will
 * first look for the property in a tag; if not found,
 * it will look through the stylesheet.
 *
 * Note: do not precede the id with a # -- it will be
 * appended when searching the stylesheets
 *
 */
function getIdProperty( id, property )
{
    if (isNav6)
    {
        var styleObject = document.getElementById( id );
        if (styleObject != null)
        {
            styleObject = styleObject.style;
            if (styleObject[property])
            {
                return styleObject[ property ];
            }
        }
        styleObject = getStyleBySelector( "#" + id );
        return (styleObject != null) ?
            styleObject[property] :
            null;
    }
    else if (isNav4)
    {
        return document[id][property];
    }
    else
    {
        return document.all[id].style[property];
    }
}

/*
 *
 * Given an id and a property (as strings), set
 * the given property of that id to the value provided.
 *
 * The property is set directly on the tag, not in the
 * stylesheet.
 *
 */
function setIdProperty( id, property, value )
{
    if (isNav6)
    {
        var styleObject = document.getElementById( id );
        if (styleObject != null)
        {
            styleObject = styleObject.style;
            styleObject[ property ] = value;
        }
    }
    else if (isNav4)
    {
        document[id][property] = value;
    }
    else if (isIE4)
    {
         document.all[id].style[property] = value;
    }
}

/*
 *
 * Move a given id.  If additive is true,
 * then move it by xValue dots horizontally and
 * yValue units vertically.  If additive is
 * false, then move it to (xValue, yValue)
 *
 * Note: do not precede the id with a # -- it will be
 * appended when searching the stylesheets
 *
 * Note also: length units are preserved in Navigator 6
 * and Internet Explorer. That is, if left is 2cm and
 * top is 3cm, and you move to (4, 5), the left will
 * become 4cm and the top 5cm.
 *
 */
function generic_move( id, xValue, yValue, additive )
{
    var left = getIdProperty(id, "left");
    var top = getIdProperty(id, "top");
    var leftMatch, topMatch;

    if (isNav4)
    {
        leftMatch = new Array( 0, left, "");
        topMatch = new Array( 0, top, "");
    }
    else if (isNav6 || isIE4 )
    {
        var splitexp = /([-0-9.]+)(\w+)/;
        leftMatch = splitexp.exec( left );
        topMatch = splitexp.exec( top );
        if (leftMatch == null || topMatch == null)
        {
            leftMatch = new Array(0, 0, "px");
            topMatch = new Array(0, 0, "px");
        }
    }
    left = ((additive) ? parseFloat( leftMatch[1] ) : 0) + xValue;
    top = ((additive) ? parseFloat( topMatch[1] ) : 0) + yValue;
    setIdProperty( id, "left", left + leftMatch[2] );
    setIdProperty( id, "top", top + topMatch[2] );
}

/*
 *
 * Move a given id to position (xValue, yValue)
 *
 */
function moveTo( id, x, y )
{
    generic_move( id, x, y, false );
}

/*
 *
 * Move a given id to (currentX + xValue, currentY + yValue)
 *
 */
function moveBy( id, x, y)
{
    generic_move( id, x, y, true );
}

/*
 *
 * Function used when converting rgb format colors
 * from Navigator 6 to a hex format
 *
 */ 
function hex( n )
{
    var hexdigits = "0123456789abcdef";
    return ( hexdigits.charAt(n >> 4) + hexdigits.charAt(n & 0x0f) );
}

/*
 *
 * Retrieve background color for a given id.
 * The value returned will be in hex format (#rrggbb)
 *
 */ 
function getBackgroundColor( id )
{
    var color;

    if (isNav4)
    {
        color = document[id].bgColor;
    }
    else if (isNav6)
    {
        var parseExp = /rgb.(\d+),(\d+),(\d+)./;
        var rgbvals;
        color = getIdProperty( id, "backgroundColor" );
        if (color)
        {
            rgbvals = parseExp.exec( color );
            if (rgbvals)
            {
                color = "#" + hex( rgbvals[1] ) + hex( rgbvals[2] ) +
                    hex( rgbvals[3] );
            }
        }
        return color;
    }
    else if (isIE4)
    {
        return document.all[id].backgroundColor;
    }
    return "";
}

/*
 *
 * Return a division''s document
 * 
 */
function getDocument( divName )
{
    var doc;

    if (isNav4)
    {
        doc = window.document[divName].document;
    }
    else if (isNav6)
    {
        doc = document;
    }
    else if (isIE4)
    {
        doc = document;
    }
    return doc;
}

function findOwner( evt )
{
    var node;
    if (isNav6)
    {
        node = evt.target;
        while (node)
        {
            if ( node.nodeType == Node.ELEMENT_NODE &&
                 node.nodeName == "DIV")
            {
                return node;
            }
            node = node.parentNode;
        }
    }
    else if (isIE4)
    {
        node = window.event.srcElement;
        while (node)
        {
            if (node.tagName == "DIV")
            {
                return node;
            }
            node = node.parentElement;
        }
    }
    return null;
}

function highlight( evt )
{
    var divObj = findOwner( evt );
    if (isNav6) { divObj.style.cursor = "pointer"; }
}

function dim( evt )
{
    var divObj = findOwner( evt );
    if (isNav6) { divObj.style.cursor = "default"; }
    divObj.style.color = "#000000";
}

function getObject( nameStr )
{
    if (isNav6)
    {
        return document.getElementById( nameStr );
    }
    else if (isIE4)
    {
        return document.all[nameStr];
    }
}


function showMenu( evt )
{
    var owner = findOwner( evt );
    var divNum;

    if (isNav6)
    {
        divNum = owner.attributes.getNamedItem("id").nodeValue;
    }
    else if (isIE4)
    {
        divNum = owner.id;
    }

    divNum = parseInt( divNum.substr(1));

    if (getIdProperty( "s" + divNum, "display") != "block" )
    {
        setIdProperty("s" + divNum, "display", "block");
    }
    else
    {
        setIdProperty("s" + divNum, "display", "none");
    }
}

function setupAction( node )
{
    if (isNav6)
    {
        node.addEventListener( "click", showMenu, false);
        node.addEventListener( "mouseover", highlight, false );
        node.addEventListener( "mouseout", dim, false );
        node.style.fontWeight = "bold";
    }
    else if (isIE4)
    {
        node.onclick = showMenu;
        node.onmouseover = highlight;
        node.onmouseout = dim;
    }
}

function setupEvents()
{
    var i;
    var theNode;

    for (i=0; i<vocabList.length; i++)
    {
        theNode = document.getElementById( "s" + i );
        setupAction( theNode );
    }
}

function setup()
{
    var i;
    var obj;

    for (i=1; i < '"$ID"'; i++)
    {
        obj = getObject( "m" + i );
        setupAction( obj );
    }
}

setBrowser();

// -->
</script>
<style type="text/css">
<!--

.submenu {
    display:none;
    margin-left: 2em;
    margin-right: 2em;
    padding: 3px;
}

.mhead {
    font-family: monospace;
    margin-left: 1em;
    margin-right: 1em;
    display: block;
    margin-bottom: 10px;
    background-color: #f8f0cc;
    border: 1px solid;
}

.header {
    margin-top: 0px;
    margin-bottom: 0px;
    padding: 5px;
    background-color: #f6f6f6;
    font-size: 10pt;
}

h3 {
    font-size: 15pt;
    letter-spacing: +1pt;
    margin-top: 25pt;
    margin-bottom: 10pt;
}

h1 {
    font-size: 30pt;
    font-weight: bold;
    margin-bottom: 5pt;
    text-align: center;
}

h5 { 
    text-align: center;
    font-size: 12pt;
    font-style: italic;
    margin: auto;
    margin-bottom: 20pt;
}

-->
</style>

<body onload="setup();">
<h1>'"$PROJECT"'</h1><h5>'"$NOTE""$CONTENT</body></html>" > $1

